### ISSUE TITLE
Option Prices: repeated error on NAN instead of valid double

### ISSUE THREAD

**Issue by higgsja** [studerw/td-ameritrade-client#36]
Not on every symbol but for example:
`[main] INFO TDA_HTTP - RESPONSE [200 - OK]: https://api.tdameritrade.com/v1/marketdata/chains?symbol=AMZN in 236.1 ms
[main] WARN com.studerw.tda.parse.BigDecimalNanDeserializer - volatility using invalid NAN instead of a valid double
[main] WARN com.studerw.tda.parse.BigDecimalNanDeserializer - delta using invalid NAN instead of a valid double
[main] WARN com.studerw.tda.parse.BigDecimalNanDeserializer - gamma using invalid NAN instead of a valid double
[main] WARN com.studerw.tda.parse.BigDecimalNanDeserializer - theta using invalid NAN instead of a valid double
[main] WARN com.studerw.tda.parse.BigDecimalNanDeserializer - rho using invalid NAN instead of a valid double
[main] WARN com.studerw.tda.parse.BigDecimalNanDeserializer - theoreticalOptionValue using invalid NAN instead of a valid double
[main] WARN com.studerw.tda.parse.BigDecimalNanDeserializer - volatility using invalid NAN instead of a valid double
`

**Comment by studerw** [comment]
Are you using the latest version 2.3.0?

**Comment by higgsja** [comment]
I think so as it is in the POM.

Is there a way to tell other than the version number there?

**Comment by studerw** [comment]
I just noticed. Those aren't really errors, they're just warning you that the JSON that's being returned is setting a bunch of JSON doubles back as the string NAN instead of 0 which they actually are, I believe (or some other number that can't be described such as -infinity). Either way, by the time the Java POJO is returned to you, those fields are set to 0, which is accurate as far as the API is concerned. 

There was another issue that was kind of similar, and apparently TDA isn't going to fix it: [https://github.com/studerw/td-ameritrade-client/issues/24](https://github.com/studerw/td-ameritrade-client/issues/24)

**Comment by studerw** [comment]
Going to close this, as I just tested Master with "AMZN" and it successfully returns the results.
