### ISSUE TITLE
Duplicate class / NoSuchMethodError

### ISSUE THREAD

**Issue by TychoTheTaco** [studerw/td-ameritrade-client#41]
I'm trying to use this library on Android 10, but I get a lot of build errors:
```
Duplicate class javax.validation.BootstrapConfiguration found in modules jetified-jakarta.validation-api-2.0.2 (jakarta.validation:jakarta.validation-api:2.0.2) and jetified-validation-api-2.0.1.Final (javax.validation:validation-api:2.0.1.Final)
Duplicate class javax.validation.ClockProvider found in modules jetified-jakarta.validation-api-2.0.2 (jakarta.validation:jakarta.validation-api:2.0.2) and jetified-validation-api-2.0.1.Final (javax.validation:validation-api:2.0.1.Final)
Duplicate class javax.validation.Configuration found in modules jetified-jakarta.validation-api-2.0.2 (jakarta.validation:jakarta.validation-api:2.0.2) and jetified-validation-api-2.0.1.Final (javax.validation:validation-api:2.0.1.Final)
(many more similar lines)
```

I have tried to get around this by specifying the dependency like this:
```
implementation ("com.studerw.tda:td-ameritrade-client:2.4.0") {
    exclude group: "javax.validation"
}
```
This makes the build successful and I'm able to use some parts of the library, but when I try to call `client.fetchTransactions()` then I get a runtime error: 
```
java.lang.NoSuchMethodError: No virtual method getAnnotatedInterfaces()[Ljava/lang/reflect/AnnotatedType; in class Ljava/lang/Class; or its super classes (declaration of 'java.lang.Class' appears in /apex/com.android.runtime/javalib/core-oj.jar)
```

Any suggestions on how to get it working on Android?

**Comment by studerw** [comment]
Do you know where that "jetified-jakarta.validation-api-2.0.2" is coming from. Basically the Java Validation is an api, and so you have to include an implementation of it. Almost all projects use a few of the standard implementation from the Jakarta eclipse project these days, but for some reason some dependency in your project is including the "Jetified" version which I've never ever heard of and cannot find anything about on Google.

Instead of trying to exlude the javax.validation, can you exclude the Jetified-jakarta stuff?
