### ISSUE TITLE
placeOrder

### ISSUE THREAD

**Issue by vbirbrayer** [studerw/td-ameritrade-client#43]
Great job on the api.  Would it be possible to return the id of the newly created order after the call?

Thanks,
Vlad

**Comment by studerw** [comment]
@vbirbrayer  I don't think this is possible, because on the backend, the request to create an order doesn't actually know if it has been successfully queued or not or if it has even been placed. Other people have had issues with this, and the only solution I know about is sleeping for a little bit, and then checking the server for the id of the new request. 

Somebody had once mentioned that in the call to place an order, TDA returns a redirect URL in the headers to a call that might be able to get the status, but I can't find that guy's comment, and so it needs some more investigation.
